package pro.leaco.curiosity.db.g.service;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table biz_data
 */
public class GDataDto {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   摘要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.abs
     *
     * @mbg.generated
     */
    private String abs;

    /**
     * Database Column Remarks:
     *   抓取类型[origin(0):原始网页,ref(1):引用网页]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     * Database Column Remarks:
     *   内容类型[html(0):HTML,text(1):纯文本,image(2):图片,sound(3):声音]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.content_type
     *
     * @mbg.generated
     */
    private Short contentType;

    /**
     * Database Column Remarks:
     *   使用的分析器
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.analysiser
     *
     * @mbg.generated
     */
    private String analysiser;

    /**
     * Database Column Remarks:
     *   优先级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     * Database Column Remarks:
     *   来源URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   详细数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     * Database Column Remarks:
     *   跳转url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_data.to_url
     *
     * @mbg.generated
     */
    private String toUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    public static String TABLE = "biz_data";

    /**
     * Database Column Remarks:
     *   ID
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.id
     *
     * @return the value of biz_data.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * Database Column Remarks:
     *   ID
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.id
     *
     * @param id the value for biz_data.id
     *
     * @mbg.generated
     */
    public GDataDto withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * Database Column Remarks:
     *   ID
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.id
     *
     * @param id the value for biz_data.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Database Column Remarks:
     *   标题
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.title
     *
     * @return the value of biz_data.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * Database Column Remarks:
     *   标题
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.title
     *
     * @param title the value for biz_data.title
     *
     * @mbg.generated
     */
    public GDataDto withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * Database Column Remarks:
     *   标题
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.title
     *
     * @param title the value for biz_data.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Database Column Remarks:
     *   摘要
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.abs
     *
     * @return the value of biz_data.abs
     *
     * @mbg.generated
     */
    public String getAbs() {
        return abs;
    }

    /**
     * Database Column Remarks:
     *   摘要
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.abs
     *
     * @param abs the value for biz_data.abs
     *
     * @mbg.generated
     */
    public GDataDto withAbs(String abs) {
        this.setAbs(abs);
        return this;
    }

    /**
     * Database Column Remarks:
     *   摘要
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.abs
     *
     * @param abs the value for biz_data.abs
     *
     * @mbg.generated
     */
    public void setAbs(String abs) {
        this.abs = abs;
    }

    /**
     * Database Column Remarks:
     *   抓取类型[origin(0):原始网页,ref(1):引用网页]
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.type
     *
     * @return the value of biz_data.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * Database Column Remarks:
     *   抓取类型[origin(0):原始网页,ref(1):引用网页]
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.type
     *
     * @param type the value for biz_data.type
     *
     * @mbg.generated
     */
    public GDataDto withType(Short type) {
        this.setType(type);
        return this;
    }

    /**
     * Database Column Remarks:
     *   抓取类型[origin(0):原始网页,ref(1):引用网页]
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.type
     *
     * @param type the value for biz_data.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * Database Column Remarks:
     *   内容类型[html(0):HTML,text(1):纯文本,image(2):图片,sound(3):声音]
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.content_type
     *
     * @return the value of biz_data.content_type
     *
     * @mbg.generated
     */
    public Short getContentType() {
        return contentType;
    }

    /**
     * Database Column Remarks:
     *   内容类型[html(0):HTML,text(1):纯文本,image(2):图片,sound(3):声音]
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.content_type
     *
     * @param contentType the value for biz_data.content_type
     *
     * @mbg.generated
     */
    public GDataDto withContentType(Short contentType) {
        this.setContentType(contentType);
        return this;
    }

    /**
     * Database Column Remarks:
     *   内容类型[html(0):HTML,text(1):纯文本,image(2):图片,sound(3):声音]
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.content_type
     *
     * @param contentType the value for biz_data.content_type
     *
     * @mbg.generated
     */
    public void setContentType(Short contentType) {
        this.contentType = contentType;
    }

    /**
     * Database Column Remarks:
     *   使用的分析器
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.analysiser
     *
     * @return the value of biz_data.analysiser
     *
     * @mbg.generated
     */
    public String getAnalysiser() {
        return analysiser;
    }

    /**
     * Database Column Remarks:
     *   使用的分析器
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.analysiser
     *
     * @param analysiser the value for biz_data.analysiser
     *
     * @mbg.generated
     */
    public GDataDto withAnalysiser(String analysiser) {
        this.setAnalysiser(analysiser);
        return this;
    }

    /**
     * Database Column Remarks:
     *   使用的分析器
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.analysiser
     *
     * @param analysiser the value for biz_data.analysiser
     *
     * @mbg.generated
     */
    public void setAnalysiser(String analysiser) {
        this.analysiser = analysiser;
    }

    /**
     * Database Column Remarks:
     *   优先级
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.priority
     *
     * @return the value of biz_data.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Database Column Remarks:
     *   优先级
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.priority
     *
     * @param priority the value for biz_data.priority
     *
     * @mbg.generated
     */
    public GDataDto withPriority(Integer priority) {
        this.setPriority(priority);
        return this;
    }

    /**
     * Database Column Remarks:
     *   优先级
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.priority
     *
     * @param priority the value for biz_data.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * Database Column Remarks:
     *   来源URL
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.url
     *
     * @return the value of biz_data.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * Database Column Remarks:
     *   来源URL
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.url
     *
     * @param url the value for biz_data.url
     *
     * @mbg.generated
     */
    public GDataDto withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * Database Column Remarks:
     *   来源URL
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.url
     *
     * @param url the value for biz_data.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Database Column Remarks:
     *   详细数据
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.data
     *
     * @return the value of biz_data.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * Database Column Remarks:
     *   详细数据
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.data
     *
     * @param data the value for biz_data.data
     *
     * @mbg.generated
     */
    public GDataDto withData(String data) {
        this.setData(data);
        return this;
    }

    /**
     * Database Column Remarks:
     *   详细数据
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.data
     *
     * @param data the value for biz_data.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * Database Column Remarks:
     *   跳转url
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_data.to_url
     *
     * @return the value of biz_data.to_url
     *
     * @mbg.generated
     */
    public String getToUrl() {
        return toUrl;
    }

    /**
     * Database Column Remarks:
     *   跳转url
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.to_url
     *
     * @param toUrl the value for biz_data.to_url
     *
     * @mbg.generated
     */
    public GDataDto withToUrl(String toUrl) {
        this.setToUrl(toUrl);
        return this;
    }

    /**
     * Database Column Remarks:
     *   跳转url
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_data.to_url
     *
     * @param toUrl the value for biz_data.to_url
     *
     * @mbg.generated
     */
    public void setToUrl(String toUrl) {
        this.toUrl = toUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", abs=").append(abs);
        sb.append(", type=").append(type);
        sb.append(", contentType=").append(contentType);
        sb.append(", analysiser=").append(analysiser);
        sb.append(", priority=").append(priority);
        sb.append(", url=").append(url);
        sb.append(", data=").append(data);
        sb.append(", toUrl=").append(toUrl);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GDataDto other = (GDataDto) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getAbs() == null ? other.getAbs() == null : this.getAbs().equals(other.getAbs()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getContentType() == null ? other.getContentType() == null : this.getContentType().equals(other.getContentType()))
            && (this.getAnalysiser() == null ? other.getAnalysiser() == null : this.getAnalysiser().equals(other.getAnalysiser()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()))
            && (this.getToUrl() == null ? other.getToUrl() == null : this.getToUrl().equals(other.getToUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getAbs() == null) ? 0 : getAbs().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getContentType() == null) ? 0 : getContentType().hashCode());
        result = prime * result + ((getAnalysiser() == null) ? 0 : getAnalysiser().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
        result = prime * result + ((getToUrl() == null) ? 0 : getToUrl().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    public static enum Column {
        id("id", "id", "BIGINT", false),
        title("title", "title", "VARCHAR", false),
        abs("abs", "abs", "VARCHAR", true),
        type("type", "type", "SMALLINT", true),
        contentType("content_type", "contentType", "SMALLINT", false),
        analysiser("analysiser", "analysiser", "VARCHAR", false),
        priority("priority", "priority", "INTEGER", false),
        url("url", "url", "LONGVARCHAR", false),
        data("data", "data", "LONGVARCHAR", true),
        toUrl("to_url", "toUrl", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String as() {
            return this.getEscapedColumnName() + " AS " + this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String as(String alias) {
            return this.getEscapedColumnName() + " AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String count() {
            return "COUNT(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String countAs() {
            return "COUNT(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String countAs(String alias) {
            return "COUNT(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String sum() {
            return "SUM(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String sumAs() {
            return "SUM(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String sumAs(String alias) {
            return "SUM(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String year() {
            return "YEAR(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String yearWeekMondayFirst() {
            return "YEARWEEK(date_format(" + this.getEscapedColumnName() + " , '%Y-%m-%d'),1)";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String yearWeekMondayFirstAs() {
            return "YEARWEEK(date_format(" + this.getEscapedColumnName() + " , '%Y-%m-%d'),1) AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String yearWeekMondayFirstAs(String alias) {
            return "YEARWEEK(date_format(" + this.getEscapedColumnName() + " , '%Y-%m-%d'),1) AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String yearAs() {
            return "YEAR(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String yearAs(String alias) {
            return "YEAR(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfYear() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAYOFYEAR(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d')";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfYearAs() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAYOFYEAR(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfYearAs(String alias) {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAYOFYEAR(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String quarter() {
            return "QUARTER(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String quarterAs() {
            return "QUARTER(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String quarterAs(String alias) {
            return "QUARTER(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String month() {
            return "MONTH(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String monthAs() {
            return "MONTH(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String monthAs(String alias) {
            return "MONTH(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfMonth() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAY(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d')";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfMonthAs() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAY(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfMonthAs(String alias) {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAY(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfWeek() {
            return "DATE_FORMAT(DATE_ADD(" + this.getEscapedColumnName() + " , INTERVAL -WEEKDAY(" + this.getEscapedColumnName() + ") DAY) ,'%Y-%m-%d')";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfWeekAs() {
            return "DATE_FORMAT(DATE_ADD(" + this.getEscapedColumnName() + " , INTERVAL -WEEKDAY(" + this.getEscapedColumnName() + ") DAY) ,'%Y-%m-%d') AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String firstDayOfWeekAs(String alias) {
            return "DATE_FORMAT(DATE_ADD(" + this.getEscapedColumnName() + " , INTERVAL -WEEKDAY(" + this.getEscapedColumnName() + ") DAY) ,'%Y-%m-%d') AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String day() {
            return "DAY(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dayAs() {
            return "DAY(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dayAs(String alias) {
            return "DAY(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String toDays() {
            return "TO_DAYS(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String toDaysAs() {
            return "TO_DAYS(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String toDaysAs(String alias) {
            return "TO_DAYS(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormat(String pattern) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"" + pattern + "\")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatAs(String pattern) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"" + pattern + "\") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatAs(String pattern, String alias) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"" + pattern + "\") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMdd$() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d\")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMdd$As() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d\") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMdd$As(String alias) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d\") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMddHHmmss$() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d %T\")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMddHHmmss$As() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d %T\") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMddHHmmss$As(String alias) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d %T\") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateSub(String param) {
            return "DATE_SUB(" + this.getEscapedColumnName() + " , " + param + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateSubAs(String param) {
            return "DATE_SUB(" + this.getEscapedColumnName() + " , " + param + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String dateSubAs(String param, String alias) {
            return "DATE_SUB(" + this.getEscapedColumnName() + " , " + param + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String withAlias() {
            if (this.isColumnNameDelimited) {
                return "biz_data." + BEGINNING_DELIMITER + this.column + ENDING_DELIMITER;
            } else {
                return "biz_data." + this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String withAlias(String as) {
            if (this.isColumnNameDelimited) {
                return "biz_data." + BEGINNING_DELIMITER + this.column + ENDING_DELIMITER + " as " + as;
            } else {
                return "biz_data." + this.column + " as " + as;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return BEGINNING_DELIMITER + this.column + ENDING_DELIMITER;
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    public static enum Type {
        ORIGIN(new Short("0"), "原始网页"),
        REF(new Short("1"), "引用网页");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final Short value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        Type(Short value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public Short getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public Short value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public static java.util.Optional<Type> parse(Short value) {
            if(value==null){
                return java.util.Optional.empty();
            }
            for (Type o: values()) {
                if(o.value.equals(value)){
                    return java.util.Optional.ofNullable(o);
                }
            }
            return java.util.Optional.empty();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    public static enum ContentType {
        HTML(new Short("0"), "HTML"),
        TEXT(new Short("1"), "纯文本"),
        IMAGE(new Short("2"), "图片"),
        SOUND(new Short("3"), "声音");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final Short value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        ContentType(Short value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public Short getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public Short value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table biz_data
         *
         * @mbg.generated
         */
        public static java.util.Optional<ContentType> parse(Short value) {
            if(value==null){
                return java.util.Optional.empty();
            }
            for (ContentType o: values()) {
                if(o.value.equals(value)){
                    return java.util.Optional.ofNullable(o);
                }
            }
            return java.util.Optional.empty();
        }
    }
}