package pro.leaco.curiosity.db.g.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import pro.leaco.curiosity.db.g.service.GDataDto;
import pro.leaco.curiosity.db.g.service.GDataDtoExample;

public interface GDataDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    long countByExample(GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    int deleteByExample(GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    int insert(GDataDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    int insertSelective(GDataDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    GDataDto selectOneByExample(GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    GDataDto selectOneByExampleSelective(@Param("example") GDataDtoExample example, @Param("selective") GDataDto.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    Map selectOneToMap(@Param("example") GDataDtoExample example, @Param("expressions") String ... expressions);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    GDataDto selectOneByExampleWithBLOBs(GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    List<GDataDto> selectByExampleSelective(@Param("example") GDataDtoExample example, @Param("selective") GDataDto.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    List<Map> selectToMap(@Param("example") GDataDtoExample example, @Param("expressions") String ... expressions);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    List<GDataDto> selectByExampleWithBLOBs(GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    List<GDataDto> selectByExample(GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GDataDto record, @Param("example") GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GDataDto record, @Param("example") GDataDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GDataDto record, @Param("example") GDataDtoExample example);
}